### ISSUE TITLE
Change back to Life360

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [ZinkNotTheMetal/HomeAssistant#12]
Custom component needed

Was much more stable than OwnTracks

Resources:
https://community.home-assistant.io/t/life360-device-tracker-platform/52406

https://github.com/pnbruckner/homeassistant-config

**Comment by ZinkNotTheMetal** [comment]
```
- alias: Location - Set xxxx Driving

  trigger:
    - platform: template
      value_template: "{{is_state_attr('device_tracker.xxxx', 'in_transit', true)}}"

  action:
    - service: device_tracker.see
      data:
        dev_id: xxxx
        location_name: 'Driving'
```
In the action, the dev_id is the device trackers name. For example, say my device tracker item is device_tracker.joe_ the value for dev_id would be ‘joe_’ (minus the quotes).
